# Generated by Django 5.0.6 on 2024-05-22 16:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='core.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 16, 36, 21, 262184, tzinfo=datetime.timezone.utc), verbose_name='Fecha Caducidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='line',
            field=models.CharField(choices=[('RS', 'Rio Store'), ('FS', 'Ferrisariato'), ('CS', 'Comisariato')], default='CS', max_length=2, verbose_name='Línea'),
        ),
    ]
