# Generated by Django 5.0.6 on 2024-05-27 19:30

import django.core.validators
import proy_sales.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_supplier_foto_alter_supplier_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Marca'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener entre 9 y 15 dígitos.', regex='^\\d{9,15}$')], verbose_name='Nº Celular'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='ruc',
            field=models.CharField(max_length=13, validators=[proy_sales.utils.valida_cedula, proy_sales.utils.valida_ruc], verbose_name='*Ruc / C.I'),
        ),
    ]
