# Generated by Django 5.0.6 on 2024-05-29 16:33

import proy_sales.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_brand_description_alter_supplier_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='core_suppli_name_c90f73_idx',
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default='brands/default.png', null=True, upload_to='brands/', verbose_name='Imagen Marca'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=20, validators=[proy_sales.utils.valida_telefono_ecuador], verbose_name='Nº Celular'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='ruc',
            field=models.CharField(max_length=13, validators=[proy_sales.utils.valida_ruc_o_cedula], verbose_name='*Ingrese Ruc/ C.I'),
        ),
    ]
