# Generated by Django 4.1 on 2024-05-31 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_category_description_alter_product_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default='brands/default.jpg', null=True, upload_to='brands/', verbose_name='Imagen Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 17, 2, 18, 138052, tzinfo=datetime.timezone.utc), verbose_name='Fecha Caducidad'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='foto',
            field=models.ImageField(blank=True, default='suppliers/default.jpg', null=True, upload_to='suplier/'),
        ),
    ]
